### ISSUE TITLE
please fix

### ISSUE THREAD

**Issue by Dephi73** [domzae/EavesDrop#1]
1x EavesDrop\EavesDrop-v2.59.lua:640: attempt to compare nil with number
EavesDrop\EavesDrop-v2.59.lua:640: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by domzae** [comment]
should be fixed now!

**Comment by Dephi73** [comment]
Thx
