### ISSUE TITLE
now

### ISSUE THREAD

**Issue by Dephi73** [domzae/EavesDrop#2]
new error

3x EavesDrop\EavesDrop-v2.59.lua:645: bad argument #4 to 'string_format' (string expected, got nil)
[C]: ?
EavesDrop\EavesDrop-v2.59.lua:645: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by domzae** [comment]
Well hopefully it is fixed now - otherwise turning off reputation event might work. Alternatively it could be helpful if you are able to tell me what you are doing when you get the error - since I've never seen it on my end and it's not my code!

**Comment by Dephi73** [comment]
Thank you. Great work👍
