### ISSUE TITLE
Error while copy pasting in chat

### ISSUE THREAD

**Issue by Ecatombe86** [domzae/EavesDrop#3]
Date: 2018-08-15 21:12:32
ID: 2
Error occured in: Global
Count: 1
Message: SendChatMessage(): Invalid escape code in chat message
Debug:
   [C]: ?
   [C]: ?
   WIM\Modules\WhisperEngine.lua:636: SendChatMessage()
   ..\FrameXML\ChatFrame.lua:4420:
      ..\FrameXML\ChatFrame.lua:4395
   [C]: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4432:
      ..\FrameXML\ChatFrame.lua:4428
   [C]: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
(*temporary) = "09:12:27 Your Melee hit Training Dummy 1,489 Physical. "
(*temporary) = "SAY"
(*temporary) = 7

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  ACP, vr259 
  AddOnSkins, v3.89
  AtlasLoot, vv8.08.00beta2
  AtlasLootBurningCrusade, vv8.08.00beta2
  AtlasLootCataclysm, vv8.08.00beta2
  AtlasLootClassic, vv8.08.00beta2
  AtlasLootLegion, vv8.08.00beta2
  AtlasLootMistsofPandaria, vv8.08.00beta2
  AtlasLootWarlordsofDraenor, vv8.08.00beta2
  AtlasLootWrathoftheLichKing, vv8.08.00beta2
  DBMCore, v8.0.2-1-g7839e5b8d
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DSM, v3.14
  EavesDrop, v2.59
  ElvUI, v10.77
  ElvUIVisualAuraTimers, v1.54
  HandyNotes, vv1.5.3
  HandyNotesArgus, v0.20.0
  Hekili, vv8.0.1-17-beta2
  kgPanels, vr448
  KrysDamageFont, v2.0b
  LibSharedMedia30, v3.0-106
  LoseControl, v5.41
  Mapster, v1.8.0
  Masque, v8.0.1
  MasqueAbstract, vwow6.0.2-2.0
  MasqueApathy, v8.0.0
  MasqueBamboo, v1
  MasqueCaith, v8.0.0
  MasqueCards, v6.2.0
  MasqueCirque, v8.0.0
  MasqueCleanIcons, v1.5
  MasqueCleanUI, v8.0.1
  MasqueDarion, v4.1.2
  MasqueDark, v3.1.0
  MasqueDarkscail, v1
  MasqueDiabloIII, v1.6
  MasqueElegance, v6.2.0
  MasqueEleganceLegion, v1.0
  MasqueEleganceLegion2, v1.0
  MasqueElvUIesque, v1.0
  MasqueEntropy, v8.0.0
  MasqueFlatSquares, v1.0.7
  MasqueGears, v8.0.0
  MasqueGmSr, v801-2018081101
  MasqueGoldpaw, v1.0
  MasqueGrunge, v1
  MasqueHelloKitty, v7.0.00
  MasqueImoen, v1.0.1
  MasqueJigsaw, v6.2.0
  MasqueKenzo, v2.0.0
  MasqueLiteStep, v8.0.0
  MasqueMuq, v7.2.1
  MasqueOnyx, v8.0.0
  masqueparabole, v6.0.0.1
  MasqueRenaitre, vv7.0.3
  MasqueSerenity, v8.0.0
  MasqueShadow, vv6.2.2
  MasqueSimpleSquare, v7.1.0.0
  MasqueSleek, v6.2.0
  MasqueSonata, v1.0.2
  MasqueStylo, vv7.2.0
  MasqueTones, v6.2.0
  MasqueTrinity, vCentauri-4
  MasqueVista, v2.0.4
  MasterPlanA, vA
  nibRealUIBossSkins, vv1.0.9
  OmniCC, v8.0.1
  OmniCCShine, v1.1.2
  Pawn, v2.2.26
  pError, v30300.4-Release
  Prat30, vr1176      
  Prat30Libraries, v
  Quartz, v3.4.0-3-g65bcdc4
  SavedInstances, v8.0.5
  SexyMap, vv8.0.7
  SharedMedia, v3.0.5-184
  SharedMediaAdditionalFonts, v1.0
  Simulationcraft, v1.10.4
  SlideBar, v7.3.1 (<%codename%>)
  WeakAuras, v2.7.2
  WIM, v3.7.18
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=93d)

**Comment by domzae** [comment]
I never got this error - but I just pushed a fix for pasting to chat, so let me know if this error goes away

**Comment by Ecatombe86** [comment]
Thanks, I can confirm it's now correctly working!
